export const Message = {
	UNAUTHORIZED_ACTION: "Sem permissão de ação",
	UNAUTHORIZED_ACCESS: "Sem permissão de acesso",
	JWT_MALFORMATED: "Jwt incorreto",
	USERNAME_OR_PASSWORD_INCORRECT: "Usuario ou senha incorretos",
	LOGIN_SUCCESS: "Login realizado com sucesso",
	LOGOUT_SUCCESS: "Desconectou com sucesso",
	USER_CREATED: "Usuario criado com sucesso",
	USER_NOT_FOUND: "Usuário não encontrado",
	DUPLICATED_NAME: "Nome já utilizado",
	NAME_REQUIRED: "Nome obrigatório",
	TOKEN_NOT_PROVIDED: "Token não informado",
	POLL_NOT_FOUND: "Quiz não encontrado",
	INVALID_ID: "Id inválido",
	MISSING_FIELDS: "Todos os campos são obrigatórios",
	INVALID_TYPE: "Tipo de requisição inválida",
	VOTE_ALREDY_DONE: "Voto ja efetuado para essa questão",
	USER_NOT_FOUND_OR_NOT_OWNER: "Usuario não encontrado ou não é dono do quiz",
	USER_ALREADY_IN_GAME: "O usuário já está na partida.",
	NO_USERS: "O quiz não possuí nenhum jogador registrado.",
	NO_QUESTIONS: "O quiz não possuí nenhuma questão.",
	INVALID_NAME: "Nome inválido",
	INVALID_PASSWORD: "A senha deve conter pelo menos 8 caracteres",
} as const;
